export const FONTS = {
  SFProRoundedRegular: require('../assets/fonts/SF-Pro-Rounded-Regular.otf'),
  SFProRoundedBlack: require('../assets/fonts/SF-Pro-Rounded-Black.otf'),
  SFProRoundedBold: require('../assets/fonts/SF-Pro-Rounded-Bold.otf'),
  SFProRoundedHeavy: require('../assets/fonts/SF-Pro-Rounded-Heavy.otf'),
  SFProRoundedLight: require('../assets/fonts/SF-Pro-Rounded-Light.otf'),
  SFProRoundedMedium: require('../assets/fonts/SF-Pro-Rounded-Medium.otf'),
  SFProRoundedSemibold: require('../assets/fonts/SF-Pro-Rounded-Semibold.otf'),
  SFProRoundedThin: require('../assets/fonts/SF-Pro-Rounded-Thin.otf'),
  SFProRoundedUltralight: require('../assets/fonts/SF-Pro-Rounded-Ultralight.otf'),
}

export const pictures = [
  {
    topPos: 80,
    leftPos: 80,
    width: 100,
    height: 100,
    toValue: 18,
    uri: 'https://lh3.googleusercontent.com/5S3Lewdf8R-9X4NUAKl_YcVeyEnHt_kRLcJo-fQNT-xiWLnMQMYIJY9ic99UM8ozWSxwEWLCAuI40kuY8K5quJ6_lvoCPUbyglQ_jQ',
  },
  {
    topPos: 100,
    leftPos: 280,
    width: 60,
    height: 60,
    toValue: 19,
    uri: 'https://lh3.googleusercontent.com/I7vZbHZU6UDm4aLlzkvoBqLBN6iDs2LogYFAOjV9yJYMfALj1RHApfcm4jqm3phLOW4CdOPSAIiKHkQXf2iRlNRArs9qVYdN-je0bnE',
  },
  {
    topPos: 210,
    leftPos: 260,
    width: 75,
    height: 75,
    toValue: 16,
    uri: 'https://lh3.googleusercontent.com/jJsUhpTNA_9CwMePUgJZamQW1IIHQgt3Hx1of8Y8EHhKqBsjHU9xb03S79xXzqLpGCVUX243N8dxYNkKaRcc51pFQh6bwZg5F8f-Ig',
  },
  {
    topPos: 220,
    leftPos: 30,
    width: 100,
    height: 100,
    toValue: 14,
    uri: 'https://lh3.googleusercontent.com/bdECg069zBNQ-8uaxdTrNMdILTElSW4tSZ0zUFSrAuCAJOmqR6TKPigPrfk-ZAN6GS7mNWjuv3qGCxx2NGJ_3Zli9FCOdDvrxh10',
  },
  {
    topPos: 490,
    leftPos: 260,
    width: 100,
    height: 100,
    toValue: 13,
    uri: 'https://lh3.googleusercontent.com/GcrfgBFUBnOJqUdoCGCG88dWYTK4Ke9qQ17frHOHCv76kpE4dhBeKsZL1vRtmpa1LXa4q29V8ZhyzUKiYj1YX4ZQAkKiGpwtrDlISw',
  },
  {
    topPos: 490,
    leftPos: 50,
    width: 63,
    height: 63,
    toValue: 20,
    uri: 'https://lh3.googleusercontent.com/k78mU3QBfrdNQWeUnNyA58QqvauTyuP_EhBScyBn57mWeejziJYn9QYG1NSyZ_75lb-auW0EwagEtQ2irbrcSP48',
  },
]
